### ISSUE TITLE
epoch

### ISSUE THREAD

**Issue by Atcold** [wojzaremba/lstm#8]
Why `epoch` are not integers? Isn't an `epoch` the training shots one performs?

```
epoch = 0.004
epoch = 0.104
epoch = 0.204
epoch = 0.304
epoch = 0.404
epoch = 0.504
epoch = 0.604
epoch = 0.703
```

**Comment by wojzaremba** [comment]
0.1 of epoch means that epoch got finished in 10%.

**Comment by Atcold** [comment]
Oh, gotcha! It's an ongoing update of the current epoch!

I just finished running the script and... does it spit any result / trained model? (I'm still trying to understand what this code is supposed to do. I guess I need to read the article :grimacing:)

**Comment by emergix** [comment]
congratulation !
Good paper
Good code , it runs the first time I try it !  
I use a Titan X, the 1h job took 25 mn !
